### ISSUE TITLE
4.7.1 does not build on OSX El Capitan

### ISSUE THREAD

**Issue by marr** [mnichols/node-mmd#4]
Output from `npm i mmd@4.7.1`
https://gist.github.com/b1a6e489bb549a5690a8

**Comment by marr** [comment]
```
$ npm i -S mmd@4.7.1
\
> mmd@4.7.1 preinstall /Users/dmarr/src/metalsmith-multimarkdown/node_modules/mmd
> make preinstall

./bin/compile-multimarkdown.sh
Cloning into 'MultiMarkdown-4'...
remote: Counting objects: 2797, done.
remote: Total 2797 (delta 0), reused 0 (delta 0), pack-reused 2797
Receiving objects: 100% (2797/2797), 4.50 MiB | 3.62 MiB/s, done.
Resolving deltas: 100% (1945/1945), done.
Checking connectivity... done.
Note: checking out '3083076038cdaceb666581636ef9e1fc68472ff0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Submodule 'MarkdownTest' (https://github.com/fletcher/MMD-Test-Suite.git) registered for path 'MarkdownTest'
Submodule 'Support' (https://github.com/fletcher/MMD-Support.git) registered for path 'Support'
Submodule 'cheat-sheet' (https://github.com/fletcher/human-markdown-reference.git) registered for path 'cheat-sheet'
Submodule 'documentation' (https://github.com/fletcher/MultiMarkdown-4.git) registered for path 'documentation'
Submodule 'greg' (https://github.com/nddrylliog/greg.git) registered for path 'greg'
Cloning into 'MarkdownTest'...
remote: Counting objects: 2501, done.
remote: Total 2501 (delta 0), reused 0 (delta 0), pack-reused 2501
Receiving objects: 100% (2501/2501), 659.22 KiB | 1.16 MiB/s, done.
Resolving deltas: 100% (1691/1691), done.
Checking connectivity... done.
Submodule path 'MarkdownTest': checked out '6984661b0cdf75a083fa6c06a9073da19abc1599'
Cloning into 'Support'...
remote: Counting objects: 338, done.
remote: Total 338 (delta 0), reused 0 (delta 0), pack-reused 338
Receiving objects: 100% (338/338), 64.66 KiB | 0 bytes/s, done.
Resolving deltas: 100% (167/167), done.
Checking connectivity... done.
Submodule path 'Support': checked out '685c95cf39a0db0c7e1067dfcf5dd2ad27dba08f'
Cloning into 'cheat-sheet'...
remote: Counting objects: 260, done.
remote: Total 260 (delta 0), reused 0 (delta 0), pack-reused 260
Receiving objects: 100% (260/260), 374.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (119/119), done.
Checking connectivity... done.
Submodule path 'cheat-sheet': checked out '199dae83cfd22254a7b329450e48aaedb8d4d2e9'
Cloning into 'documentation'...
remote: Counting objects: 2797, done.
remote: Total 2797 (delta 0), reused 0 (delta 0), pack-reused 2797
Receiving objects: 100% (2797/2797), 4.50 MiB | 4.12 MiB/s, done.
Resolving deltas: 100% (1945/1945), done.
Checking connectivity... done.
Submodule path 'documentation': checked out 'c1bc09342a516f318a6b2f3e7e259bc09d9c9513'
Cloning into 'greg'...
remote: Counting objects: 435, done.
remote: Total 435 (delta 0), reused 0 (delta 0), pack-reused 435
Receiving objects: 100% (435/435), 197.23 KiB | 0 bytes/s, done.
Resolving deltas: 100% (214/214), done.
Checking connectivity... done.
Submodule path 'greg': checked out '98ecf13c3502b47e342b09fb7b0cad453e1bb797'
Makefile:65: warning: overriding commands for target `/usr/local/bin'
Makefile:56: warning: ignoring old commands for target `/usr/local/bin'
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o multimarkdown.o multimarkdown.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o parse_utilities.o parse_utilities.c
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C greg
cc -g -Wall -O3 -DNDEBUG    -c -o greg.o greg.c
cc -g -Wall -O3 -DNDEBUG    -c -o tree.o tree.c
cc -g -Wall -O3 -DNDEBUG    -c -o compile.o compile.c
cc -g -Wall -O3 -DNDEBUG  -o greg-new greg.o tree.o compile.o
mv greg-new greg
greg/greg -o parser.c parser.leg
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o parser.o parser.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o GLibFacade.o GLibFacade.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o writer.o writer.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o text.o text.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o html.o html.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o latex.o latex.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o memoir.o memoir.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o beamer.o beamer.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o lyx.o lyx.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o lyxbeamer.o lyxbeamer.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o opml.o opml.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o odf.o odf.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o critic.o critic.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o rng.o rng.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o rtf.o rtf.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o transclude.o transclude.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o toc.o toc.c
cc -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -L/opt/boxen/homebrew/lib -o multimarkdown multimarkdown.o parse_utilities.o parser.o GLibFacade.o writer.o text.o html.o latex.o memoir.o beamer.o lyx.o lyxbeamer.o opml.o odf.o critic.o rng.o rtf.o transclude.o toc.o
./enumsToPerl.pl libMultiMarkdown.h enumMap.txt
npm install nan
nan@2.1.0 node_modules/nan
npm install node-gyp
node-gyp@3.1.0 node_modules/node-gyp
├── graceful-fs@4.1.2
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── semver@5.0.3
├── nopt@3.0.6 (abbrev@1.0.7)
├── which@1.2.0 (is-absolute@0.1.7)
├── fstream@1.0.8 (inherits@2.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.0)
├── glob@4.5.3 (inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.10)
├── path-array@1.0.0 (array-index@0.1.1)
├── rimraf@2.4.3 (glob@5.0.15)
├── tar@2.2.1 (inherits@2.0.1, block-stream@0.0.8)
├── npmlog@1.2.1 (ansi@0.3.0, gauge@1.2.2, are-we-there-yet@1.0.4)
└── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.1, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, combined-stream@1.0.5, qs@5.2.0, tough-cookie@2.2.1, mime-types@2.1.7, form-data@1.0.0-rc3, http-signature@0.11.0, bl@1.0.0, hawk@3.1.1, har-validator@2.0.2)
./node_modules/.bin/node-gyp configure --debug
./node_modules/.bin/node-gyp build --debug
  CXX(target) Debug/obj.target/mmd/src/mmd.o
../src/mmd.cc:13:17: error: use of undeclared identifier 'NanNew'
    target->Set(NanNew<v8::String>("convert"),
                ^
../src/mmd.cc:13:34: error: expected '(' for function-style cast or type construction
    target->Set(NanNew<v8::String>("convert"),
                       ~~~~~~~~~~^
../src/mmd.cc:14:13: error: use of undeclared identifier 'NanNew'
            NanNew<v8::FunctionTemplate>(Convert)->GetFunction());
            ^
../src/mmd.cc:14:40: error: expected '(' for function-style cast or type construction
            NanNew<v8::FunctionTemplate>(Convert)->GetFunction());
                   ~~~~~~~~~~~~~~~~~~~~^
../src/mmd.cc:14:50: error: member reference base type 'Nan::NAN_METHOD_RETURN_TYPE
      (Nan::NAN_METHOD_ARGS_TYPE)' is not a structure or union
            NanNew<v8::FunctionTemplate>(Convert)->GetFunction());
                                        ~~~~~~~~~^ ~~~~~~~~~~~
../src/mmd.cc:16:17: error: use of undeclared identifier 'NanNew'
    target->Set(NanNew<v8::String>("extractMetadataKeys"),
                ^
../src/mmd.cc:16:34: error: expected '(' for function-style cast or type construction
    target->Set(NanNew<v8::String>("extractMetadataKeys"),
                       ~~~~~~~~~~^
../src/mmd.cc:17:13: error: use of undeclared identifier 'NanNew'
            NanNew<v8::FunctionTemplate>(ExtractMetadataKeys)->GetFunction());
            ^
../src/mmd.cc:17:40: error: expected '(' for function-style cast or type construction
            NanNew<v8::FunctionTemplate>(ExtractMetadataKeys)->GetFunction());
                   ~~~~~~~~~~~~~~~~~~~~^
../src/mmd.cc:17:62: error: member reference base type 'Nan::NAN_METHOD_RETURN_TYPE
      (Nan::NAN_METHOD_ARGS_TYPE)' is not a structure or union
            NanNew<v8::FunctionTemplate>(ExtractMetadataKeys)->GetFunction());
                                        ~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~
../src/mmd.cc:19:17: error: use of undeclared identifier 'NanNew'
    target->Set(NanNew<v8::String>("extractMetadataValue"),
                ^
../src/mmd.cc:19:34: error: expected '(' for function-style cast or type construction
    target->Set(NanNew<v8::String>("extractMetadataValue"),
                       ~~~~~~~~~~^
../src/mmd.cc:20:13: error: use of undeclared identifier 'NanNew'
            NanNew<v8::FunctionTemplate>(ExtractMetadataValue)->GetFunction());
            ^
../src/mmd.cc:20:40: error: expected '(' for function-style cast or type construction
            NanNew<v8::FunctionTemplate>(ExtractMetadataValue)->GetFunction());
                   ~~~~~~~~~~~~~~~~~~~~^
../src/mmd.cc:20:63: error: member reference base type 'Nan::NAN_METHOD_RETURN_TYPE
      (Nan::NAN_METHOD_ARGS_TYPE)' is not a structure or union
            NanNew<v8::FunctionTemplate>(ExtractMetadataValue)->GetFunction());
                                        ~~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~
15 errors generated.
make[1]: *** [Debug/obj.target/mmd/src/mmd.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/dmarr/src/metalsmith-multimarkdown/node_modules/mmd/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/opt/boxen/nodenv/versions/iojs-v2.5.0/bin/iojs" "/Users/dmarr/src/metalsmith-multimarkdown/node_modules/mmd/node_modules/.bin/node-gyp" "build" "--debug"
gyp ERR! cwd /Users/dmarr/src/metalsmith-multimarkdown/node_modules/mmd
gyp ERR! node -v v2.5.0
gyp ERR! node-gyp -v v3.1.0
gyp ERR! not ok
make: *** [build/Release/mmd.node] Error 1
npm ERR! Darwin 15.0.0
npm ERR! argv "/opt/boxen/nodenv/versions/iojs-v2.5.0/bin/iojs" "/opt/boxen/nodenv/versions/iojs-v2.5.0/bin/npm" "i" "-S" "mmd@4.7.1"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE

npm ERR! mmd@4.7.1 preinstall: `make preinstall`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mmd@4.7.1 preinstall script 'make preinstall'.
npm ERR! This is most likely a problem with the mmd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dmarr/src/metalsmith-multimarkdown/npm-debug.log
```

**Comment by marr** [comment]
and with node v5.0.0

```
$ npm i -S mmd@4.7.1

> mmd@4.7.1 preinstall /Users/dmarr/src/metalsmith-multimarkdown/node_modules/.staging/mmd-ff1e3dba7d534020c31a489da6f86345
> make preinstall

./bin/compile-multimarkdown.sh
Cloning into 'MultiMarkdown-4'...
remote: Counting objects: 2797, done.
remote: Total 2797 (delta 0), reused 0 (delta 0), pack-reused 2797
Receiving objects: 100% (2797/2797), 4.50 MiB | 3.58 MiB/s, done.
Resolving deltas: 100% (1945/1945), done.
Checking connectivity... done.
Note: checking out '3083076038cdaceb666581636ef9e1fc68472ff0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Submodule 'MarkdownTest' (https://github.com/fletcher/MMD-Test-Suite.git) registered for path 'MarkdownTest'
Submodule 'Support' (https://github.com/fletcher/MMD-Support.git) registered for path 'Support'
Submodule 'cheat-sheet' (https://github.com/fletcher/human-markdown-reference.git) registered for path 'cheat-sheet'
Submodule 'documentation' (https://github.com/fletcher/MultiMarkdown-4.git) registered for path 'documentation'
Submodule 'greg' (https://github.com/nddrylliog/greg.git) registered for path 'greg'
Cloning into 'MarkdownTest'...
remote: Counting objects: 2501, done.
remote: Total 2501 (delta 0), reused 0 (delta 0), pack-reused 2501
Receiving objects: 100% (2501/2501), 659.22 KiB | 1.11 MiB/s, done.
Resolving deltas: 100% (1691/1691), done.
Checking connectivity... done.
Submodule path 'MarkdownTest': checked out '6984661b0cdf75a083fa6c06a9073da19abc1599'
Cloning into 'Support'...
remote: Counting objects: 338, done.
remote: Total 338 (delta 0), reused 0 (delta 0), pack-reused 338
Receiving objects: 100% (338/338), 64.66 KiB | 0 bytes/s, done.
Resolving deltas: 100% (167/167), done.
Checking connectivity... done.
Submodule path 'Support': checked out '685c95cf39a0db0c7e1067dfcf5dd2ad27dba08f'
Cloning into 'cheat-sheet'...
remote: Counting objects: 260, done.
remote: Total 260 (delta 0), reused 0 (delta 0), pack-reused 260
Receiving objects: 100% (260/260), 374.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (119/119), done.
Checking connectivity... done.
Submodule path 'cheat-sheet': checked out '199dae83cfd22254a7b329450e48aaedb8d4d2e9'
Cloning into 'documentation'...
remote: Counting objects: 2797, done.
remote: Total 2797 (delta 0), reused 0 (delta 0), pack-reused 2797
Receiving objects: 100% (2797/2797), 4.50 MiB | 3.79 MiB/s, done.
Resolving deltas: 100% (1945/1945), done.
Checking connectivity... done.
Submodule path 'documentation': checked out 'c1bc09342a516f318a6b2f3e7e259bc09d9c9513'
Cloning into 'greg'...
remote: Counting objects: 435, done.
remote: Total 435 (delta 0), reused 0 (delta 0), pack-reused 435
Receiving objects: 100% (435/435), 197.23 KiB | 0 bytes/s, done.
Resolving deltas: 100% (214/214), done.
Checking connectivity... done.
Submodule path 'greg': checked out '98ecf13c3502b47e342b09fb7b0cad453e1bb797'
Makefile:65: warning: overriding commands for target `/usr/local/bin'
Makefile:56: warning: ignoring old commands for target `/usr/local/bin'
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o multimarkdown.o multimarkdown.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o parse_utilities.o parse_utilities.c
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C greg
cc -g -Wall -O3 -DNDEBUG    -c -o greg.o greg.c
cc -g -Wall -O3 -DNDEBUG    -c -o tree.o tree.c
cc -g -Wall -O3 -DNDEBUG    -c -o compile.o compile.c
cc -g -Wall -O3 -DNDEBUG  -o greg-new greg.o tree.o compile.o
mv greg-new greg
greg/greg -o parser.c parser.leg
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o parser.o parser.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o GLibFacade.o GLibFacade.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o writer.o writer.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o text.o text.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o html.o html.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o latex.o latex.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o memoir.o memoir.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o beamer.o beamer.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o lyx.o lyx.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o lyxbeamer.o lyxbeamer.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o opml.o opml.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o odf.o odf.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o critic.o critic.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o rng.o rng.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o rtf.o rtf.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o transclude.o transclude.c
cc -c -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -o toc.o toc.c
cc -fPIC -Wall -O3 -include GLibFacade.h -include parser.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE -L/opt/boxen/homebrew/lib -o multimarkdown multimarkdown.o parse_utilities.o parser.o GLibFacade.o writer.o text.o html.o latex.o memoir.o beamer.o lyx.o lyxbeamer.o opml.o odf.o critic.o rng.o rtf.o transclude.o toc.o
./enumsToPerl.pl libMultiMarkdown.h enumMap.txt
npm install nan
mmd@4.7.1 /Users/dmarr/src/metalsmith-multimarkdown/node_modules/.staging/mmd-ff1e3dba7d534020c31a489da6f86345
└── nan@2.1.0

npm install node-gyp
mmd@4.7.1 /Users/dmarr/src/metalsmith-multimarkdown/node_modules/.staging/mmd-ff1e3dba7d534020c31a489da6f86345
└─┬ node-gyp@3.1.0
  ├─┬ fstream@1.0.8
  │ └── inherits@2.0.1
  ├─┬ glob@4.5.3
  │ ├─┬ inflight@1.0.4
  │ │ └── wrappy@1.0.1
  │ ├─┬ minimatch@2.0.10
  │ │ └─┬ brace-expansion@1.1.1
  │ │   ├── balanced-match@0.2.1
  │ │   └── concat-map@0.0.1
  │ └── once@1.3.2
  ├── graceful-fs@4.1.2
  ├─┬ minimatch@1.0.0
  │ ├── lru-cache@2.7.0
  │ └── sigmund@1.0.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ nopt@3.0.6
  │ └── abbrev@1.0.7
  ├─┬ npmlog@1.2.1
  │ ├── ansi@0.3.0
  │ ├─┬ are-we-there-yet@1.0.4
  │ │ ├── delegates@0.1.0
  │ │ └─┬ readable-stream@1.1.13
  │ │   ├── core-util-is@1.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ └─┬ gauge@1.2.2
  │   ├── has-unicode@1.0.1
  │   ├─┬ lodash.pad@3.1.1
  │   │ ├── lodash._basetostring@3.0.1
  │   │ └─┬ lodash._createpadding@3.6.1
  │   │   └── lodash.repeat@3.0.1
  │   ├── lodash.padleft@3.1.1
  │   └── lodash.padright@3.1.1
  ├─┬ osenv@0.1.3
  │ ├── os-homedir@1.0.1
  │ └── os-tmpdir@1.0.1
  ├─┬ path-array@1.0.0
  │ └─┬ array-index@0.1.1
  │   └─┬ debug@2.2.0
  │     └── ms@0.7.1
  ├─┬ request@2.65.0
  │ ├── aws-sign2@0.6.0
  │ ├─┬ bl@1.0.0
  │ │ └─┬ readable-stream@2.0.4
  │ │   ├── process-nextick-args@1.0.3
  │ │   └── util-deprecate@1.0.2
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@1.0.0-rc3
  │ │ └── async@1.5.0
  │ ├─┬ har-validator@2.0.2
  │ │ ├─┬ chalk@1.1.1
  │ │ │ ├── ansi-styles@2.1.0
  │ │ │ ├── escape-string-regexp@1.0.3
  │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ ├── strip-ansi@3.0.0
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ ├─┬ is-my-json-valid@2.12.3
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@2.0.0
  │ │ │ └── xtend@4.0.1
  │ │ └─┬ pinkie-promise@1.0.0
  │ │   └── pinkie@1.0.0
  │ ├─┬ hawk@3.1.1
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@0.11.0
  │ │ ├── asn1@0.1.11
  │ │ ├── assert-plus@0.1.5
  │ │ └── ctype@0.5.3
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.7
  │ │ └── mime-db@1.19.0
  │ ├── node-uuid@1.4.7
  │ ├── oauth-sign@0.8.0
  │ ├── qs@5.2.0
  │ ├── stringstream@0.0.5
  │ ├── tough-cookie@2.2.1
  │ └── tunnel-agent@0.4.1
  ├─┬ rimraf@2.4.3
  │ └─┬ glob@5.0.15
  │   ├── minimatch@3.0.0
  │   └── path-is-absolute@1.0.0
  ├── semver@5.0.3
  ├─┬ tar@2.2.1
  │ └── block-stream@0.0.8
  └─┬ which@1.2.0
    └─┬ is-absolute@0.1.7
      └── is-relative@0.1.3

./node_modules/.bin/node-gyp configure --debug
./node_modules/.bin/node-gyp build --debug
  CXX(target) Debug/obj.target/mmd/src/mmd.o
../src/mmd.cc:13:17: error: use of undeclared identifier 'NanNew'
    target->Set(NanNew<v8::String>("convert"),
                ^
../src/mmd.cc:13:34: error: expected '(' for function-style cast or type construction
    target->Set(NanNew<v8::String>("convert"),
                       ~~~~~~~~~~^
../src/mmd.cc:14:13: error: use of undeclared identifier 'NanNew'
            NanNew<v8::FunctionTemplate>(Convert)->GetFunction());
            ^
../src/mmd.cc:14:40: error: expected '(' for function-style cast or type construction
            NanNew<v8::FunctionTemplate>(Convert)->GetFunction());
                   ~~~~~~~~~~~~~~~~~~~~^
../src/mmd.cc:14:50: error: member reference base type 'Nan::NAN_METHOD_RETURN_TYPE
      (Nan::NAN_METHOD_ARGS_TYPE)' is not a structure or union
            NanNew<v8::FunctionTemplate>(Convert)->GetFunction());
                                        ~~~~~~~~~^ ~~~~~~~~~~~
../src/mmd.cc:16:17: error: use of undeclared identifier 'NanNew'
    target->Set(NanNew<v8::String>("extractMetadataKeys"),
                ^
../src/mmd.cc:16:34: error: expected '(' for function-style cast or type construction
    target->Set(NanNew<v8::String>("extractMetadataKeys"),
                       ~~~~~~~~~~^
../src/mmd.cc:17:13: error: use of undeclared identifier 'NanNew'
            NanNew<v8::FunctionTemplate>(ExtractMetadataKeys)->GetFunction());
            ^
../src/mmd.cc:17:40: error: expected '(' for function-style cast or type construction
            NanNew<v8::FunctionTemplate>(ExtractMetadataKeys)->GetFunction());
                   ~~~~~~~~~~~~~~~~~~~~^
../src/mmd.cc:17:62: error: member reference base type 'Nan::NAN_METHOD_RETURN_TYPE
      (Nan::NAN_METHOD_ARGS_TYPE)' is not a structure or union
            NanNew<v8::FunctionTemplate>(ExtractMetadataKeys)->GetFunction());
                                        ~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~
../src/mmd.cc:19:17: error: use of undeclared identifier 'NanNew'
    target->Set(NanNew<v8::String>("extractMetadataValue"),
                ^
../src/mmd.cc:19:34: error: expected '(' for function-style cast or type construction
    target->Set(NanNew<v8::String>("extractMetadataValue"),
                       ~~~~~~~~~~^
../src/mmd.cc:20:13: error: use of undeclared identifier 'NanNew'
            NanNew<v8::FunctionTemplate>(ExtractMetadataValue)->GetFunction());
            ^
../src/mmd.cc:20:40: error: expected '(' for function-style cast or type construction
            NanNew<v8::FunctionTemplate>(ExtractMetadataValue)->GetFunction());
                   ~~~~~~~~~~~~~~~~~~~~^
../src/mmd.cc:20:63: error: member reference base type 'Nan::NAN_METHOD_RETURN_TYPE
      (Nan::NAN_METHOD_ARGS_TYPE)' is not a structure or union
            NanNew<v8::FunctionTemplate>(ExtractMetadataValue)->GetFunction());
                                        ~~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~
15 errors generated.
make[1]: *** [Debug/obj.target/mmd/src/mmd.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/dmarr/src/metalsmith-multimarkdown/node_modules/.staging/mmd-ff1e3dba7d534020c31a489da6f86345/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/opt/boxen/nodenv/versions/v5.0.0/bin/node" "/Users/dmarr/src/metalsmith-multimarkdown/node_modules/.staging/mmd-ff1e3dba7d534020c31a489da6f86345/node_modules/.bin/node-gyp" "build" "--debug"
gyp ERR! cwd /Users/dmarr/src/metalsmith-multimarkdown/node_modules/.staging/mmd-ff1e3dba7d534020c31a489da6f86345
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.1.0
gyp ERR! not ok
make: *** [build/Release/mmd.node] Error 1
npm ERR! Darwin 15.0.0
npm ERR! argv "/opt/boxen/nodenv/versions/v5.0.0/bin/node" "/opt/boxen/nodenv/versions/v5.0.0/bin/npm" "i" "-S" "mmd@4.7.1"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! mmd@4.7.1 preinstall: `make preinstall`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mmd@4.7.1 preinstall script 'make preinstall'.
npm ERR! This is most likely a problem with the mmd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dmarr/src/metalsmith-multimarkdown/npm-debug.log
```

**Comment by mnichols** [comment]
Looks like some nan errors b/c node5 isnt supported yet.

**Comment by marr** [comment]
I tried with 4.2.1 as well and had the same issue.

**Comment by mnichols** [comment]
Ok I will see what I can do.
